[package]
name = "up-transport-iceoryx2-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
up-rust = "0.5"
iceoryx2 = "0.6.1"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.6"  
protobuf = "3.7.2"
